version: "3.7"

services:
  db:
    image: "mysql:5.6"
    container_name: "mysql_5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    ports:
      - "3356:3306"
    volumes:
      - ~/.docker-stack/mysql/56:/var/lib/mysql
    networks:
      - mysql

networks:
  mysql:
   name: mysql