version: "3.7"

services:
  db:
    image: "mysql:latest"
    container_name: "mysql_latest"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    ports:
      - "3306:3306"
    volumes:
      - ~/.docker-stack/mysql/latest:/var/lib/mysql
    networks:
      - mysql

networks:
  mysql:
   name: mysql